### ISSUE TITLE
Spots

### ISSUE THREAD

**Issue by jiangtt18** [jiangtt18/Castlebnb#3]
- [x] Spots
   - [x] Adequate styling
   - [x]  Adequate and appropriate seeds to demonstrate feature
    - [x] spots can be shown on index page
    - [x] single spot can be shown on show page

**Comment by dwebster17** [comment]
Great Job! 

+ Right now, when I refresh a castle page, the image disappears. I vaguely remember us fixing this yesterday, so maybe it's because the latest version isn't up?

+ Very small styling suggestion for the index page: 
  + The item-info looks a little crowded. You can give the `.item-index-info` div a `margin-top` of around 5px
  + Every `<p>` tag element that is a child of `.item-index-info` could have a margin-bottom of around `3px` so they are separated just a bit.
